# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PF37H5L0iNF246cmIcqnFy1qQN3VP5MH
"""

# ==============================
# STREAMLIT APP – TV SHOW ANALYTICS
# ==============================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import ast
import warnings
warnings.filterwarnings("ignore")

st.set_page_config(
    page_title="TV Shows Analytics Dashboard",
    layout="wide"
)

sns.set(style="whitegrid")

# ==============================
# DATA LOADING
# ==============================
@st.cache_data
def load_data():
    df = pd.read_csv("10k_Poplar_Tv_Shows_with_users_updated6.csv")

    df["genre_names"] = df["genre_names"].apply(
        lambda x: ast.literal_eval(x) if isinstance(x, str) else x
    )

    df["origin_country"] = df["origin_country"].apply(
        lambda x: ast.literal_eval(x) if isinstance(x, str) else x
    )

    df["first_air_date"] = pd.to_datetime(df["first_air_date"], errors="coerce")
    df["year"] = df["first_air_date"].dt.year

    return df

df = load_data()

# ==============================
# SIDEBAR – NAV + FILTERS
# ==============================
st.sidebar.title("Navigation")
section = st.sidebar.radio(
    "Go to",
    [
        "Overview",
        "User Age Analysis",
        "Genre Analysis",
        "Binge Watching",
        "Time of Day",
        "Country Analysis",
        "Trends Over Time",
        "Additional Analyses"
    ]
)

# ---- Global filters (age range + genres) ----
age_min = int(df["user_age"].min()) if "user_age" in df.columns else 0
age_max = int(df["user_age"].max()) if "user_age" in df.columns else 100

all_genres = sorted(
    {g for lst in df["genre_names"].dropna() for g in lst}
) if "genre_names" in df.columns else []

# Init session_state defaults
if "age_filter" not in st.session_state:
    st.session_state["age_filter"] = (age_min, age_max)
if "genre_filter" not in st.session_state:
    st.session_state["genre_filter"] = []

def reset_filters():
    st.session_state["age_filter"] = (age_min, age_max)
    st.session_state["genre_filter"] = []

st.sidebar.markdown("---")
st.sidebar.subheader("Filters")

# Age group (range) filter
if age_min < age_max:
    age_filter = st.sidebar.slider(
        "User age range",
        age_min,
        age_max,
        st.session_state["age_filter"],
        key="age_filter",
    )
else:
    age_filter = (age_min, age_max)

# Genre filter
selected_genres = st.sidebar.multiselect(
    "Genres",
    options=all_genres,
    default=st.session_state["genre_filter"],
    key="genre_filter",
    help="Leave empty to include all genres.",
)

# Reset button
if st.sidebar.button("Reset filters"):
    reset_filters()

# Apply filters to a working dataframe
filtered_df = df.copy()

if "user_age" in filtered_df.columns and age_filter:
    filtered_df = filtered_df[
        (filtered_df["user_age"] >= age_filter[0])
        & (filtered_df["user_age"] <= age_filter[1])
    ]

if selected_genres:
    def has_selected_genre(genres):
        if isinstance(genres, list):
            return any(g in selected_genres for g in genres)
        return False

    filtered_df = filtered_df[filtered_df["genre_names"].apply(has_selected_genre)]

if filtered_df.empty:
    st.warning("No shows match the current filters. Try adjusting the age range or genres.")
    st.stop()

# ==============================
# OVERVIEW
# ==============================
if section == "Overview":
    st.title("📺 TV Shows Analytics Dashboard")

    st.write("### Dataset Overview")
    col_a, col_b, col_c = st.columns(3)
    with col_a:
        st.metric("Total Shows", filtered_df.shape[0])
    with col_b:
        st.metric("Average Vote", round(filtered_df["vote_average"].mean(), 2))
    with col_c:
        st.metric("Average Popularity", round(filtered_df["popularity"].mean(), 2))

    st.write("### Sample Data")
    st.dataframe(filtered_df.head(20))

    # Additional plots from projet_python_v2.py
    st.write("### Histogram of Popularity Scores")
    fig, ax = plt.subplots()
    ax.hist(filtered_df["popularity"].dropna(), bins=30)
    ax.set_xlabel("Popularity Score")
    ax.set_ylabel("Number of Shows")
    ax.set_title("Histogram of Popularity Scores")
    st.pyplot(fig)

    st.write("### Distributions of Key Metrics")
    fig, axs = plt.subplots(1, 3, figsize=(15, 4))
    sns.histplot(filtered_df["popularity"].dropna(), kde=True, ax=axs[0])
    axs[0].set_title("Distribution of Popularity")
    sns.histplot(filtered_df["vote_average"].dropna(), kde=True, ax=axs[1])
    axs[1].set_title("Distribution of Vote Average")
    sns.histplot(filtered_df["vote_count"].dropna(), kde=False, ax=axs[2])
    axs[2].set_yscale("log")
    axs[2].set_title("Distribution of Vote Count (Log Scale)")
    st.pyplot(fig)

    st.write("### Pairplot of Numeric Features")
    pair_df = filtered_df[["popularity", "vote_average", "vote_count"]].dropna()
    if not pair_df.empty:
        fig = sns.pairplot(
            pair_df,
            diag_kind="kde",
            corner=True,
        )
        st.pyplot(fig)
    else:
        st.info("Not enough data for pairplot with current filters.")

    st.write("### Correlation Heatmap of Numeric Features")
    numeric_df = filtered_df.select_dtypes(include=[np.number])
    corr = numeric_df.corr()
    fig, ax = plt.subplots(figsize=(8, 6))
    sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", ax=ax)
    ax.set_title("Correlation Heatmap of Numeric Features")
    st.pyplot(fig)

# ==============================
# USER AGE ANALYSIS
# ==============================
elif section == "User Age Analysis":
    st.title("👥 User Age Analysis")

    col1, col2 = st.columns(2)

    with col1:
        fig, ax = plt.subplots()
        ax.hist(filtered_df["user_age"].dropna(), bins=20)
        ax.set_title("Histogram of User Ages")
        ax.set_xlabel("Age")
        ax.set_ylabel("Count")
        st.pyplot(fig)

    with col2:
        fig, ax = plt.subplots()
        ax.scatter(filtered_df["vote_average"], filtered_df["vote_count"])
        ax.set_xlabel("Vote Average")
        ax.set_ylabel("Vote Count")
        ax.set_title("Vote Average vs Vote Count")
        st.pyplot(fig)

    # Additional plots
    st.write("### Average Viewing Session Duration per Age")
    if "session_duration_min" in filtered_df.columns:
        age_duration = (
            filtered_df.groupby("user_age")["session_duration_min"]
            .mean()
            .reset_index()
        )
        fig, ax = plt.subplots(figsize=(10, 6))
        ax.scatter(age_duration["user_age"], age_duration["session_duration_min"])
        ax.set_title("Average Viewing Session Duration per Age")
        ax.set_xlabel("User Age")
        ax.set_ylabel("Average Duration (min)")
        ax.grid(True)
        st.pyplot(fig)

    st.write("### Correlation Heatmap of Numerical Features")
    numeric_cols = ["popularity", "vote_average", "vote_count", "user_age"]
    existing_cols = [c for c in numeric_cols if c in filtered_df.columns]
    corr = filtered_df[existing_cols].corr()
    fig, ax = plt.subplots()
    im = ax.imshow(corr)
    ax.set_xticks(range(len(existing_cols)))
    ax.set_xticklabels(existing_cols, rotation=45)
    ax.set_yticks(range(len(existing_cols)))
    ax.set_yticklabels(existing_cols)
    plt.colorbar(im)
    ax.set_title("Correlation Heatmap of Numerical Features")
    st.pyplot(fig)

# ==============================
# GENRE ANALYSIS
# ==============================
elif section == "Genre Analysis":
    st.title("🎭 Genre Analysis")

    exploded = filtered_df.explode("genre_names")

    genre_counts = exploded["genre_names"].value_counts().head(10)

    fig, ax = plt.subplots()
    genre_counts.plot(kind="bar", ax=ax)
    ax.set_title("Top 10 Genres")
    ax.set_xlabel("Genre")
    ax.set_ylabel("Number of Shows")
    plt.xticks(rotation=45)
    st.pyplot(fig)

    st.write("### Genre vs Age Group Popularity")

    bins = [12, 17, 24, 34, 44, 54, 70]
    labels = [
        "Teen (13–17)",
        "Young Adult (18–24)",
        "Adult (25–34)",
        "Mid Adult (35–44)",
        "Older Adult (45–54)",
        "Senior (55–70)",
    ]
    ga_df = filtered_df.copy()
    ga_df["age_group"] = pd.cut(ga_df["user_age"], bins=bins, labels=labels)

    pivot = pd.pivot_table(
        ga_df.explode("genre_names"),
        values="popularity",
        index="genre_names",
        columns="age_group",
        aggfunc="mean",
    )

    fig, ax = plt.subplots(figsize=(10, 6))
    sns.heatmap(pivot, cmap="coolwarm", ax=ax)
    ax.set_title("Average Genre Popularity by Age Group")
    st.pyplot(fig)

    # Additional plots
    st.write("### Genre Liking Probability by Age")
    exploded["likes"] = exploded["vote_average"] > 7
    prob_like = (
        exploded.groupby(["user_age", "genre_names"])["likes"].mean().reset_index()
    )
    prob_like = prob_like.rename(columns={"likes": "prob_like"})
    pivot_prob = prob_like.pivot(
        index="genre_names", columns="user_age", values="prob_like"
    ).fillna(0)
    pivot_prob = pivot_prob.loc[pivot_prob.mean(axis=1).sort_values(ascending=False).index]
    fig, ax = plt.subplots(figsize=(20, 15))
    sns.heatmap(pivot_prob, cmap="YlGnBu", annot=False, linewidths=0.5, ax=ax)
    ax.set_title("Genre Liking Probability by Age")
    ax.set_xlabel("User Age")
    ax.set_ylabel("Genre")
    plt.xticks(rotation=45)
    plt.yticks(rotation=0)
    st.pyplot(fig)

    st.write("### Average Genre Popularity by Age Group (Alternative View)")
    df_genre_age = ga_df.explode("genre_names")
    pivot_genre_age = pd.pivot_table(
        df_genre_age,
        values="popularity",
        index="genre_names",
        columns="age_group",
        aggfunc="mean",
    )
    fig, ax = plt.subplots(figsize=(12, 6))
    im = ax.imshow(pivot_genre_age, aspect="auto")
    ax.set_xticks(range(len(pivot_genre_age.columns)))
    ax.set_xticklabels(pivot_genre_age.columns, rotation=45)
    ax.set_yticks(range(len(pivot_genre_age.index)))
    ax.set_yticklabels(pivot_genre_age.index)
    plt.colorbar(im, label="Average Popularity")
    ax.set_title("Average Genre Popularity by Age Group")
    st.pyplot(fig)

# ==============================
# BINGE WATCHING
# ==============================
elif section == "Binge Watching":
    st.title("🍿 Binge Watching Analysis")

    bw_df = filtered_df.copy()
    bw_df["is_binge"] = (bw_df["popularity"] > 50) & (bw_df["vote_count"] > 1000)
    bw_df["binge_prob"] = bw_df["is_binge"].astype(int) * (1 - bw_df["user_age"] / 100)

    binge_by_age = bw_df.groupby("user_age")["binge_prob"].mean()

    fig, ax = plt.subplots()
    ax.plot(binge_by_age.index, binge_by_age.values)
    ax.set_xlabel("Age")
    ax.set_ylabel("Binge Probability")
    ax.set_title("Binge Watching Probability by Age")
    st.pyplot(fig)

    # Additional plots
    st.write("### Binge-Watching Probability by Age Group and Genre")
    exploded = bw_df.explode("genre_names")
    exploded["age_group"] = pd.cut(
        exploded["user_age"], bins=[0, 20, 40, 60, 100], labels=["0-20", "21-40", "41-60", "61+"]
    )
    binge_by_group_genre = (
        exploded.groupby(["age_group", "genre_names"])["binge_prob"]
        .mean()
        .reset_index()
    )
    pivot_binge = binge_by_group_genre.pivot(
        index="genre_names", columns="age_group", values="binge_prob"
    ).fillna(0)
    pivot_binge = pivot_binge.loc[pivot_binge.mean(axis=1).sort_values(ascending=False).index]
    fig, ax = plt.subplots(figsize=(12, 15))
    sns.heatmap(pivot_binge, cmap="YlOrRd", annot=True, fmt=".2f", linewidths=0.5, ax=ax)
    ax.set_title("Binge-Watching Probability by Age Group and Genre")
    ax.set_xlabel("Age Group")
    ax.set_ylabel("Genre")
    plt.xticks(rotation=45)
    plt.yticks(rotation=0)
    st.pyplot(fig)

# ==============================
# TIME OF DAY
# ==============================
elif section == "Time of Day":
    st.title("⏰ Time of Day Watching Patterns")

    def sim_hour(age):
        if age < 20:
            mean = 21
        elif age < 40:
            mean = 20
        else:
            mean = 19
        return int(np.random.normal(mean, 2)) % 24

    np.random.seed(42)
    td_df = filtered_df.copy()
    td_df["watch_hour"] = td_df["user_age"].apply(sim_hour)

    td_df["age_group"] = pd.cut(
        td_df["user_age"],
        bins=[0, 20, 40, 60, 100],
        labels=["0-20", "21-40", "41-60", "61+"],
    )

    pivot = pd.pivot_table(
        td_df,
        index="age_group",
        columns="watch_hour",
        aggfunc="size",
        fill_value=0,
    )

    fig, ax = plt.subplots(figsize=(12, 6))
    sns.heatmap(pivot, cmap="YlGnBu", ax=ax)
    ax.set_title("Watching Time Heatmap")
    st.pyplot(fig)

# ==============================
# COUNTRY ANALYSIS
# ==============================
elif section == "Country Analysis":
    st.title("🌍 Country Analysis")

    exploded = filtered_df.explode("origin_country")
    top_countries = exploded["origin_country"].value_counts().head(10)

    fig, ax = plt.subplots()
    top_countries.plot(kind="barh", ax=ax)
    ax.set_title("Top 10 Countries by Number of Shows")
    st.pyplot(fig)

    # Additional plots
    st.write("### Age Distribution for Top Country")
    age_dist_country = (
        exploded.groupby("origin_country")["user_age"]
        .agg(["mean", "median", "std", "count"])
        .reset_index()
    )
    age_dist_country = age_dist_country.sort_values("count", ascending=False)
    top_country = age_dist_country.iloc[0]["origin_country"]
    fig, ax = plt.subplots(figsize=(10, 6))
    exploded[exploded["origin_country"] == top_country]["user_age"].hist(
        bins=20, ax=ax
    )
    ax.set_title(f"Age Distribution for {top_country}")
    ax.set_xlabel("Age")
    ax.set_ylabel("Frequency")
    ax.grid(True)
    st.pyplot(fig)

    st.write("### Count of TV Shows by Origin Country (Top 10)")
    df_country = filtered_df.explode("origin_country")
    top_countries = df_country["origin_country"].value_counts().head(10).index
    df_country_top = df_country[df_country["origin_country"].isin(top_countries)]
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.countplot(
        y="origin_country",
        data=df_country_top,
        order=top_countries,
        ax=ax,
    )
    ax.set_title("Count of TV Shows by Origin Country (Top 10)")
    ax.set_xlabel("Number of Shows")
    ax.set_ylabel("Country")
    st.pyplot(fig)

    st.write("### Average Genre Popularity by Country (Top 10 Countries)")
    df_exp = filtered_df.explode("genre_names").explode("origin_country")
    top_countries = df_exp["origin_country"].value_counts().head(10).index
    df_top = df_exp[df_exp["origin_country"].isin(top_countries)]
    pivot = pd.pivot_table(
        df_top,
        values="popularity",
        index="genre_names",
        columns="origin_country",
        aggfunc="mean",
    )
    fig, ax = plt.subplots(figsize=(12, 6))
    im = ax.imshow(pivot, aspect="auto")
    ax.set_xticks(range(len(pivot.columns)))
    ax.set_xticklabels(pivot.columns, rotation=45)
    ax.set_yticks(range(len(pivot.index)))
    ax.set_yticklabels(pivot.index)
    plt.colorbar(im, label="Average Popularity")
    ax.set_title("Average Genre Popularity by Country (Top 10 Countries)")
    st.pyplot(fig)

# ==============================
# TRENDS OVER TIME
# ==============================
elif section == "Trends Over Time":
    st.title("📈 Trends Over Time")

    trend_df = filtered_df.copy()

    exploded = trend_df.explode("genre_names")
    genre_trends = pd.pivot_table(
        exploded,
        values="popularity",
        index="year",
        columns="genre_names",
        aggfunc="mean",
    )

    top_genres = exploded["genre_names"].value_counts().head(5).index
    genre_trends = genre_trends[top_genres]

    fig, ax = plt.subplots(figsize=(10, 5))
    for g in genre_trends.columns:
        ax.plot(genre_trends.index, genre_trends[g], label=g)

    ax.set_title("Genre Popularity Trends Over Time")
    ax.set_xlabel("Year")
    ax.set_ylabel("Popularity")
    ax.legend()
    st.pyplot(fig)

    # Additional plots
    st.write("### Number of TV Shows Released per Year")
    trend_df["first_air_year"] = trend_df["first_air_date"].dt.year
    shows_per_year = trend_df["first_air_year"].value_counts().sort_index()
    fig, ax = plt.subplots()
    ax.plot(shows_per_year.index, shows_per_year.values)
    ax.set_xlabel("Year")
    ax.set_ylabel("Number of Shows")
    ax.set_title("Number of TV Shows Released per Year")
    st.pyplot(fig)

    st.write("### Genre Preference Trends Over Time")
    df_time = trend_df.dropna(subset=["year"])
    df_time_genre = df_time.explode("genre_names")
    genre_trends = pd.pivot_table(
        df_time_genre,
        values="popularity",
        index="year",
        columns="genre_names",
        aggfunc="mean",
    )
    top_genres = df_time_genre["genre_names"].value_counts().head(6).index
    genre_trends_top = genre_trends[top_genres]
    fig, ax = plt.subplots(figsize=(12, 6))
    for genre in genre_trends_top.columns:
        ax.plot(genre_trends_top.index, genre_trends_top[genre], label=genre)
    ax.set_xlabel("Year")
    ax.set_ylabel("Average Popularity")
    ax.set_title("Genre Preference Trends Over Time")
    ax.legend()
    st.pyplot(fig)

    st.write("### Normalized Genre Popularity Trends Over Time")
    genre_trends_normalized = genre_trends_top / genre_trends_top.max()
    fig, ax = plt.subplots(figsize=(12, 6))
    for genre in genre_trends_normalized.columns:
        ax.plot(genre_trends_normalized.index, genre_trends_normalized[genre], label=genre)
    ax.set_xlabel("Year")
    ax.set_ylabel("Normalized Popularity")
    ax.set_title("Normalized Genre Popularity Trends Over Time")
    ax.legend()
    st.pyplot(fig)

    st.write("### Genre Popularity Trends by Decade for Each Age Group")
    trend_df["decade"] = (trend_df["year"] // 10) * 10
    if "age_group" not in trend_df.columns:
        trend_df["age_group"] = pd.cut(
            trend_df["user_age"],
            bins=[0, 20, 40, 60, 100],
            labels=["0-20", "21-40", "41-60", "61+"],
        )
    df_age_genre = trend_df.dropna(subset=["decade", "age_group"]).explode("genre_names")
    pivot_decade = pd.pivot_table(
        df_age_genre,
        values="popularity",
        index=["decade", "age_group"],
        columns="genre_names",
        aggfunc="mean",
        observed=False,
    ).reset_index()
    top_genres = df_age_genre["genre_names"].value_counts().head(5).index
    for age in pivot_decade["age_group"].dropna().unique():
        df_plot = pivot_decade[pivot_decade["age_group"] == age]
        fig, ax = plt.subplots(figsize=(10, 5))
        for genre in top_genres:
            if genre in df_plot.columns:
                ax.plot(df_plot["decade"], df_plot[genre], marker="o", label=genre)
        ax.set_title(f"Genre Popularity Trends by Decade ({age})")
        ax.set_xlabel("Decade")
        ax.set_ylabel("Average Popularity")
        ax.legend()
        ax.grid(alpha=0.3)
        st.pyplot(fig)

# ==============================
# ADDITIONAL ANALYSES
# ==============================
elif section == "Additional Analyses":
    st.title("🔍 Additional Analyses")

    st.write("### Outliers in Vote Average")
    Q1 = filtered_df["vote_average"].quantile(0.25)
    Q3 = filtered_df["vote_average"].quantile(0.75)
    IQR = Q3 - Q1
    mask = (filtered_df["vote_average"] < (Q1 - 1.5 * IQR)) | (
        filtered_df["vote_average"] > (Q3 + 1.5 * IQR)
    )
    outliers = filtered_df.loc[mask, ["id", "name", "vote_average"]]
    st.dataframe(outliers)

    st.write("### Missing Values Report")
    missing_values = filtered_df.isnull().sum()
    st.dataframe(missing_values)

    # Any other non-plot analyses can go here
